services:
  web:
    build: .
  web_migrate:
    extends:
      service: web
    depends_on:
      - web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    depends_on:
      - web_migrate
    command: python manage.py runserver 0.0.0.0:8000
  web_gunicorn:
    extends:
      service: web
    ports:
      - "8000:8000"
    networks:
      - network-one
    depends_on:
      - web_run
    command: gunicorn --bind 0.0.0.0:8000 locallibrary.wsgi --workers=4
  nginx:
    depends_on:
      - web_gunicorn
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "80:80"
    networks:
      - network-one
networks:
  network-one:
    name: network-one
volumes:
  media_volume:
  static_volume: