services:
  web:
    build: .
    image: antonasmirko/build-django-library
  web_migrate:
    extends:
      service: web
    depends_on:
      - web
    command: python manage.py migrate
    image: antonasmirko/migrate-django-library
  web_run:
    extends:
      service: web
    depends_on:
      - web_migrate
    command: python manage.py runserver 0.0.0.0:8000
    image: antonasmirko/run-django-library
  web_gunicorn:
    extends:
      service: web
    ports:
      - "8000:8000"
    networks:
      - network-one
    depends_on:
      - web_run
    volumes:
      - admin:/code/staticfiles/admin
      - static:/code/staticfiles
    command: gunicorn --bind 0.0.0.0:8000 locallibrary.wsgi --workers=4
    image: antonasmirko/connect-to-gunicorn-django-library
  nginx:
    depends_on:
      - web_gunicorn
    build: nginx
    restart: always
    volumes:
      - static:/code/staticfiles
      - admin:/code/staticfiles/admin
    ports:
      - "80:80"
    networks:
      - network-one
    image: antonasmirko/nginx-for-django-libry
networks:
  network-one:
    name: network-one
volumes:
  static:
  admin: